# Generated by Django 5.2.17 on 2026-10-06 07:01

from django.conf import settings
from django.db import migrations, models


def expire_legacy_unpaid(apps, schema_editor):
    """Bookings made before online payment existed were never paid for and have no payment window.

    They are not assumed to be paid: every still-PENDING one becomes EXPIRED (it stops blocking its dates). CONFIRMED,
    CANCELLED and COMPLETED bookings are left exactly as they were.
    """
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(status="PENDING", expires_at__isnull=True).update(status="EXPIRED")


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("catalog", "0002_propertyimage_format_propertyimage_height_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Awaiting payment"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                    ("REFUND_REQUIRED", "Refund required"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "expires_at"], name="booking_status_expiry_idx"
            ),
        ),
        migrations.RunPython(expire_legacy_unpaid, migrations.RunPython.noop),
    ]
