# Generated by Django 5.2.17 on 2026-10-04 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Indian rupees.", max_digits=10
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="subscription_amount_not_negative",
            ),
        ),
    ]
