# Generated by Django 5.2.17 on 2026-10-07 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_subscription_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION", "Subscription"),
                            ("TOPUP", "Wallet top-up"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New subscription"),
                            ("RENEWAL", "Renewal"),
                            ("CHANGE", "Plan change"),
                            ("TRIAL", "Trial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_paise",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Plan price at the time (0 for a top-up)."
                    ),
                ),
                (
                    "credit_paise",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Value of the unused time of the replaced plan.",
                    ),
                ),
                (
                    "wallet_paise",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Taken from the wallet (credit and balance).",
                    ),
                ),
                (
                    "amount_paise",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Charged through Razorpay."
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Order created"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("SUPERSEDED", "Replaced by a newer checkout"),
                            ("REFUND_REQUIRED", "Refund required"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "verified_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHECKOUT", "Checkout verification"),
                            ("WEBHOOK", "Webhook"),
                            ("WALLET", "Wallet (no gateway charge)"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HostWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_paise", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TOPUP", "Top-up"),
                            ("SUBSCRIPTION_PAYMENT", "Subscription payment"),
                            ("PRORATION_CREDIT", "Credit for unused time"),
                            ("ADMIN_CREDIT", "Credit by Blüdhaven"),
                            ("ADMIN_DEBIT", "Debit by Blüdhaven"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "amount_paise",
                    models.BigIntegerField(
                        help_text="Positive adds to the balance, negative takes from it."
                    ),
                ),
                ("balance_after_paise", models.BigIntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False,
                help_text="Stays active to the end of the period, then CANCELLED.",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="grace_until",
            field=models.DateField(
                blank=True,
                help_text="PAST_DUE only: access continues through this day.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="previous_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription this one renewed or replaced.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_subscriptions",
                to="billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_trial",
            field=models.BooleanField(
                default=False,
                help_text="A free plan a Host can start once, with no payment. Its price must be 0.",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expiry_date",
            field=models.DateField(help_text="The day this period ends (not covered)."),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(help_text="First day of this period."),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past due"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive plans cannot be newly assigned or bought.",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("is_trial", False), ("price", 0), _connector="OR"),
                name="plan_trial_is_free",
            ),
        ),
        migrations.AddField(
            model_name="billingpayment",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_payments",
                to="billing.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="billingpayment",
            name="previous_subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription being renewed or replaced when the order was created.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="billingpayment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="The subscription this payment activated.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_payments",
                to="billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="billingpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="billing_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hostwallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="billing_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to="billing.billingpayment",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to="billing.subscription",
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="billing.hostwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="billingpayment",
            index=models.Index(
                fields=["user", "status"], name="billingpayment_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hostwallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_paise__gte", 0)),
                name="wallet_balance_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_paise", 0), _negated=True),
                name="wallettx_amount_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_after_paise__gte", 0)),
                name="wallettx_balance_after_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                fields=("billing_payment", "kind"),
                name="wallettx_once_per_payment_kind",
            ),
        ),
    ]
