# Generated by Django 5.2.17 on 2026-10-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_self_serve_billing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["display_order", "price", "name"]},
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Position on the plans pages (lowest first). Plans with the same value are ordered by price.",
            ),
        ),
        migrations.AlterField(
            model_name="billingpayment",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New subscription"),
                    ("RENEWAL", "Renewal"),
                    ("CHANGE", "Plan change"),
                    ("DOWNGRADE", "Scheduled downgrade"),
                    ("TRIAL", "Trial"),
                ],
                max_length=10,
            ),
        ),
    ]
