# Generated by Django 5.2.17 on 2026-10-04 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
            options={
                "verbose_name_plural": "amenities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("state", models.CharField(max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("CABIN", "Cabin"),
                            ("VILLA", "Villa"),
                            ("COTTAGE", "Cottage"),
                            ("APARTMENT", "Apartment"),
                            ("TENT", "Tent"),
                            ("HOUSEBOAT", "Houseboat"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "locality",
                    models.CharField(
                        blank=True,
                        help_text="Area within the destination, e.g. Assagao.",
                        max_length=120,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, help_text="Indian rupees.", max_digits=10
                    ),
                ),
                ("max_guests", models.PositiveSmallIntegerField()),
                ("bedrooms", models.PositiveSmallIntegerField(default=1)),
                ("bathrooms", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="properties", to="catalog.amenity"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to="catalog.destination",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("storage_key", models.CharField(blank=True, max_length=255)),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 is the cover photo."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["destination", "property_type"], name="property_dest_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price_per_night"], name="property_price_idx"),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_night__gt", 0)),
                name="property_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_guests__gte", 1)),
                name="property_max_guests_at_least_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="favourite_unique_user_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyimage",
            constraint=models.UniqueConstraint(
                fields=("property", "position"), name="propertyimage_unique_position"
            ),
        ),
    ]
