# Generated by Django 5.2.17 on 2026-10-07 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_propertyimage_format_propertyimage_height_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="amenity",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="address_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="property",
            name="address_line2",
            field=models.CharField(
                blank=True, help_text="Unit / apartment number.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="PUBLISHED",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["status"], name="property_status_idx"),
        ),
    ]
