# Generated by Django 5.2.17 on 2026-10-07 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_property_status_address_premium_amenity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="property",
            name="property_price_positive",
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_per_night__gt", 0), ("status", "DRAFT"), _connector="OR"
                ),
                name="property_price_positive",
            ),
        ),
    ]
