# Generated by Django 5.2.17 on 2026-10-04 10:22

import django.utils.timezone
from django.db import migrations, models


def verify_existing_super_admins(apps, schema_editor):
    """Super Admins already in the database were created on the server by an operator."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(role="SUPER_ADMIN", email_verified_at__isnull=True).update(email_verified_at=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(verify_existing_super_admins, migrations.RunPython.noop),
    ]
