# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_payment_window"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(default="razorpay", editable=False, max_length=20),
                ),
                ("razorpay_order_id", models.CharField(max_length=64, unique=True)),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("amount_paise", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Order created"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUND_REQUIRED", "Refund required"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                (
                    "verified_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHECKOUT", "Checkout verification"),
                            ("WEBHOOK", "Webhook"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["status"], name="payment_status_idx")],
            },
        ),
    ]
