import {
  Bath,
  Briefcase,
  Car,
  Check,
  Coffee,
  Dumbbell,
  Flame,
  Mountain,
  PawPrint,
  Snowflake,
  Thermometer,
  Trees,
  UtensilsCrossed,
  WashingMachine,
  Waves,
  Wifi,
} from 'lucide-react'

const icons = {
  'Wi-Fi': Wifi,
  Fireplace: Flame,
  Bonfire: Flame,
  Kitchen: UtensilsCrossed,
  'Mountain view': Mountain,
  'Lake view': Waves,
  'River view': Waves,
  'Sea view': Waves,
  'Garden view': Trees,
  'Free parking': Car,
  Heating: Thermometer,
  'Air conditioning': Snowflake,
  'Private pool': Waves,
  'Pet friendly': PawPrint,
  Barbecue: Flame,
  Workspace: Briefcase,
  Washer: WashingMachine,
  'Gym access': Dumbbell,
  'Breakfast included': Coffee,
  'Hot tub': Bath,
  'Yoga deck': Trees,
}

export const amenityIcon = (name) => icons[name] ?? Check
